const foods = [
  {
    id: 1,
    category: "food",
    name: "Pedigree PRO, 20kg Pack",
    price: 4690,
    rating: 60,
    size: null,
    rating: 80,
    description: "Item details",
    image:
      "https://images-eu.ssl-images-amazon.com/images/I/41SDby7VxpL._SY300_SX300_QL70_FMwebp_.jpg",
    images_array: [
      "https://images-eu.ssl-images-amazon.com/images/I/41SDby7VxpL._SY300_SX300_QL70_FMwebp_.jpg",
      "https://m.media-amazon.com/images/I/61pbAMWvWPL._SX679_.jpg",
      "https://m.media-amazon.com/images/I/61pbAMWvWPL._SX679_.jpg",
      "https://m.media-amazon.com/images/I/61pbAMWvWPL._SX679_.jpg",
    ],
  },
  {
    id: 2,
    category: "food",
    name: "Pedigree Wet Food for Puppy",
    price: 525,
    rating: 60,
    size: null,
    rating: 90,
    description: "Item details",
    image: "https://m.media-amazon.com/images/I/51MM+uEiWVL._SY300_SX300_.jpg",
    images_array: [
      "https://m.media-amazon.com/images/I/61pbAMWvWPL._SX679_.jpg",
      "https://m.media-amazon.com/images/I/61pbAMWvWPL._SX679_.jpg",
      "https://m.media-amazon.com/images/I/61pbAMWvWPL._SX679_.jpg",
    ],
  },
  {
    id: 3,
    category: "food",
    name: "Royal Canin Shih Tzu Adult Dry Dog Food 1.5 Kg",
    price: 1503,
    rating: 60,
    size: null,
    rating: 90,
    description: "Item details",
    image: "https://m.media-amazon.com/images/I/71CbFOjA67L._SY879_.jpg",
    images_array: [
      "https://m.media-amazon.com/images/I/61pbAMWvWPL._SX679_.jpg",
      "https://m.media-amazon.com/images/I/61pbAMWvWPL._SX679_.jpg",
      "https://m.media-amazon.com/images/I/61pbAMWvWPL._SX679_.jpg",
    ],
  },
  {
    id: 4,
    category: "food",
    name: "Kennel Kitchen Adult & Puppy Dog Food, Chicken and Lamb Chunks in Gravy, 12 Pouches",
    price: 391,
    rating: 60,
    size: null,
    rating: 90,
    description: "Item details",
    image: "https://m.media-amazon.com/images/I/51h57u0+0jL._SY300_SX300_.jpg",
    images_array: [
      "https://m.media-amazon.com/images/I/61pbAMWvWPL._SX679_.jpg",
      "https://m.media-amazon.com/images/I/61pbAMWvWPL._SX679_.jpg",
      "https://m.media-amazon.com/images/I/61pbAMWvWPL._SX679_.jpg",
    ],
  },
  {
    id: 5,
    category: "food",
    name: "Drools Chicken and Egg Adult Dry Dog Food, 10kg",
    price: 1685,
    size: null,
    rating: 90,
    description: "Item details",
    image: "https://m.media-amazon.com/images/I/61p0tyktUHL._SX679_.jpg",
    images_array: [
      "https://m.media-amazon.com/images/I/61pbAMWvWPL._SX679_.jpg",
      "https://m.media-amazon.com/images/I/61pbAMWvWPL._SX679_.jpg",
      "https://m.media-amazon.com/images/I/61pbAMWvWPL._SX679_.jpg",
    ],
  },
  {
    id: 6,
    category: "food",
    name: "Pedigree Tasty Minis Treats for Puppy, Chicken Flavour, 125g",
    price: 154,
    rating: 60,
    size: null,
    rating: 90,
    description: "Item details",
    image:
      "https://images-eu.ssl-images-amazon.com/images/I/514yocjnvyL._SX300_SY300_QL70_FMwebp_.jpg",
    images_array: [
      "https://m.media-amazon.com/images/I/61pbAMWvWPL._SX679_.jpg",
      "https://m.media-amazon.com/images/I/61pbAMWvWPL._SX679_.jpg",
      "https://m.media-amazon.com/images/I/61pbAMWvWPL._SX679_.jpg",
    ],
  },
  {
    id: 7,
    category: "food",
    name: "Drools Trumppetz Focus Adult Super Dog Food, 12kg",
    price: 4099,
    size: null,
    rating: 90,
    description: "Item details",
    image: "https://m.media-amazon.com/images/I/41WYl1Dt8ML.jpg",
    images_array: [
      "https://m.media-amazon.com/images/I/61pbAMWvWPL._SX679_.jpg",
      "https://m.media-amazon.com/images/I/61pbAMWvWPL._SX679_.jpg",
      "https://m.media-amazon.com/images/I/61pbAMWvWPL._SX679_.jpg",
    ],
  },
  {
    id: 8,
    category: "food",
    name: "Pedigree Dentastix Oral Care Treats for Small Breed Adult Dogs (5-10 kg), 28 Sticks, 440g Monthly Pack",
    price: 456,
    size: null,
    rating: 90,
    description: "Item details",
    image: "https://m.media-amazon.com/images/I/61teH4prV5L._SX679_.jpg",
    images_array: [
      "https://m.media-amazon.com/images/I/61pbAMWvWPL._SX679_.jpg",
      "https://m.media-amazon.com/images/I/61pbAMWvWPL._SX679_.jpg",
      "https://m.media-amazon.com/images/I/61pbAMWvWPL._SX679_.jpg",
    ],
  },
  {
    id: 9,
    category: "food",
    name: "Pedigree Biscrok Biscuit Treats for Dogs (Above 4 Months), Chicken Flavour, 900g Pack",
    price: 220,
    rating: 60,
    size: null,
    rating: 90,
    description: "Item details",
    image: "https://m.media-amazon.com/images/I/81Wm0e6AlpL._SX679_.jpg",
    images_array: [
      "https://m.media-amazon.com/images/I/61pbAMWvWPL._SX679_.jpg",
      "https://m.media-amazon.com/images/I/61pbAMWvWPL._SX679_.jpg",
      "https://m.media-amazon.com/images/I/61pbAMWvWPL._SX679_.jpg",
    ],
  },
  {
    id: 10,
    category: "food",
    name: "Pedigree Puppy Starter Kit",
    price: 289,
    rating: 60,
    size: null,
    rating: 90,
    description: "Item details",
    image:
      "https://cdn.shopify.com/s/files/1/0565/8021/0861/products/Frame802_720x.png?v=1661252068",
    images_array: [
      "https://m.media-amazon.com/images/I/61pbAMWvWPL._SX679_.jpg",
      "https://m.media-amazon.com/images/I/61pbAMWvWPL._SX679_.jpg",
      "https://m.media-amazon.com/images/I/61pbAMWvWPL._SX679_.jpg",
    ],
  },
];

export { foods };
